CXXFLAGS = -MMD -Wall -g -I.. -DSTATICPLUGINS

SRCS := $(wildcard *.cc)
OBJS := $(SRCS:.cc=.o)

all: $(OBJS) plugins.h

plugins.h: $(SRCS)
	chmod +x make_plugins_h
	./make_plugins_h

clean: FORCE
	rm -f $(OBJS) $(SRCS:.cc=.d) plugins.h core.*

FORCE:

-include $(SRCS:.cc=.d)
